### ISSUE TITLE
mGadgetron Makefile

### ISSUE THREAD

**Issue by DANAJK** [CCPPETMR/xGadgetron#5]
Need to remove -fopenmp flag

Makefile uses variable ISMRMRD_INCLUDE that may not exist. Fix is to add this to environment variables defined in the instructions? e.g.  ISMRMRD_INCLUDE=/Users/home/ISMRMRD/include/ismrmrd

**Comment by evgueni-ovtchinnikov** [comment]
Done (ISMRMRD_INCLUDE was not actually needed, now removed).

**Comment by DANAJK** [comment]
mGadgetron still does not compile on a Mac due to use of `-soname` flag.

```
670:~/xGadgetron/mGadgetron$ make
/usr/bin/gcc -O3 -fPIC -DNDEBUG -DGCC -I/Applications/MATLAB_R2015b.app/extern/include -I/Users/davidatkinson/iUtilities -I/Users/davidatkinson/xGadgetron/cGadgetron -c -o mutilities.o mutilities.c
/usr/bin/gcc -O3 -fPIC -DNDEBUG -DGCC \
	-shared -Wl,-soname,mutilities.mexa64 \
	-o mutilities.mexa64 mutilities.o printer.o /Users/davidatkinson/build/iUtilities/libiutil.a
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [TARGET1] Error 1
```

**Comment by evgueni-ovtchinnikov** [comment]
Please try -install_name instead of –soname.

(Cannot try myself as I have not got Mac yet.)

**Comment by DANAJK** [comment]
With `-install_name` instead of `-soname` it gets further but still is not successful:

```
742:~/xGadgetron/mGadgetron$ make
/usr/bin/gcc -O3 -fPIC -DNDEBUG -DGCC \
	-shared -Wl,-install_name,mutilities.mexa64 \
	-o mutilities.mexa64 mutilities.o printer.o /Users/davidatkinson/build/iUtilities/libiutil.a
Undefined symbols for architecture x86_64:
  "std::terminate()", referenced from:
      ___clang_call_terminate in libiutil.a(data_handle.o)
  "typeinfo for std::exception", referenced from:
      typeinfo for LocalisedException in libiutil.a(data_handle.o)
  "vtable for __cxxabiv1::__class_type_info", referenced from:
      typeinfo for aTextWriter in printer.o
      typeinfo for DataHandle in libiutil.a(data_handle.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__si_class_type_info", referenced from:
      typeinfo for mexTextPrinter in printer.o
      typeinfo for LocalisedException in libiutil.a(data_handle.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "operator delete[](void*)", referenced from:
      _copyOfObjectHandle in libiutil.a(data_handle.o)
      DataHandle::set(void*, ExecutionStatus const*, int) in libiutil.a(data_handle.o)
      DataHandle::~DataHandle() in libiutil.a(data_handle.o)
      DataHandle::~DataHandle() in libiutil.a(data_handle.o)
  "operator delete(void*)", referenced from:
      mexTextPrinter::~mexTextPrinter() in printer.o
      DataHandle::set(void*, ExecutionStatus const*, int) in libiutil.a(data_handle.o)
      DataHandle::~DataHandle() in libiutil.a(data_handle.o)
      DataHandle::~DataHandle() in libiutil.a(data_handle.o)
  "operator new[](unsigned long)", referenced from:
      _copyOfObjectHandle in libiutil.a(data_handle.o)
      DataHandle::set(void*, ExecutionStatus const*, int) in libiutil.a(data_handle.o)
  "operator new(unsigned long)", referenced from:
      _newMexPrinter in printer.o
      _newDataHandle in libiutil.a(data_handle.o)
      _copyOfObjectHandle in libiutil.a(data_handle.o)
      _charDataHandle in libiutil.a(data_handle.o)
      _intDataHandle in libiutil.a(data_handle.o)
      _floatDataHandle in libiutil.a(data_handle.o)
      _doubleDataHandle in libiutil.a(data_handle.o)
      ...
  "___cxa_begin_catch", referenced from:
      _copyOfObjectHandle in libiutil.a(data_handle.o)
      ___clang_call_terminate in libiutil.a(data_handle.o)
  "___cxa_end_catch", referenced from:
      _copyOfObjectHandle in libiutil.a(data_handle.o)
  "___gxx_personality_v0", referenced from:
      _copyOfObjectHandle in libiutil.a(data_handle.o)
      DataHandle::set(void*, ExecutionStatus const*, int) in libiutil.a(data_handle.o)
      Dwarf Exception Unwind Info (__eh_frame) in libiutil.a(data_handle.o)
  "_mexPrintf", referenced from:
      _newMexPrinter in printer.o
      mexTextPrinter::write(char const*) const in printer.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [TARGET1] Error 1 
```

**Comment by evgueni-ovtchinnikov** [comment]
Try to add –lc++ at the end (i.e. after …/libiutil.a).

**Comment by DANAJK** [comment]
OK. Now I seem to be missing a header file that I cannot find?:

```
793:~/xGadgetron/mGadgetron$ make
/usr/bin/gcc -O3 -fPIC -DNDEBUG -DGCC -I/Applications/MATLAB_R2015b.app/extern/include -I/Users/davidatkinson/iUtilities -I/Users/davidatkinson/xGadgetron/cGadgetron -c -o printer.o printer.cpp
In file included from printer.cpp:1:
./printer.h:5:10: fatal error: 'text_writer.h' file not found
#include "text_writer.h"
         ^
1 error generated.
make: *** [printer.o] Error 1
```

**Comment by evgueni-ovtchinnikov** [comment]
Just remove printer.o from Makefile (or pull the update from git).

My printing redirection does not work with Gadgetron, so I just removed it for the time being.
